apiVersion: apps/v1
kind: Deployment
metadata:
  name: uda-capstone
  labels:
    app: uda-capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uda-capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uda-capstone
    spec:
      containers:
      - image: harishkumarrajput/$CIRCLE_PROJECT_REPONAME:latest
        imagePullPolicy: Always
        name: uda-capstone
        ports:
        - containerPort: 80
          protocol: TCP
