apiVersion: v1
kind: Deployment
metadata:
  name: uda_capstone
  labels:
    app: uda_capstone
  namespace: default
spec:
  replicas: 3
  selector:
    matchLabels:
      app: uda_capstone
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: uda_capstone
    spec:
      containers:
      - image: harishkumarrajput/$CIRCLE_PROJECT_REPONAME
        imagePullPolicy: Always
        name: uda_capstone
        ports:
        - containerPort: 80
          protocol: TCP
